import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim shirt",
    slug: "nike-slim-shirt",
    image: "../images/p1.jpg",
    category: "Shirts",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "Original Nike high quality T-shirt, material cotton 100%",
  },
  {
    name: "Adidas Fit shirt",
    slug: "adidas-fit-shirt",
    image: "./images/p2.jpg",
    category: "Shirts",
    price: 100,
    countInStock: 20,
    brand: "Adidas",
    rating: 4.0,
    numReviews: 10,
    description: "Original Adidas high quality T-shirt, material cotton 100%",
  },
  {
    name: "Lacosta Free Pants",
    slug: "lacosta-free-pants",
    image: "../images/p3.jpg",
    category: "Pants",
    price: 220,
    countInStock: 0,
    brand: "lacosta",
    rating: 4.8,
    numReviews: 17,
    description: "Original Lacosta high quality Pants",
  },
  {
    name: "Nike Slim Pants",
    slug: "nike-slim-pants",
    image: "../images/p4.jpg",
    category: "Pants",
    price: 78,
    countInStock: 15,
    brand: "lacosta",
    rating: 4.5,
    numReviews: 14,
    description: "High quality original nike slim pants",
  },
];
