import { User } from "./models/userModel";
import { Product } from "./models/productModel";
import bcrypt from "bcryptjs";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim shirt",
    slug: "nike-slim-shirt",
    image: "../images/p1.jpg",
    category: "Shirts",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "Original Nike high quality T-shirt, material cotton 100%",
  },
  {
    name: "Adidas Fit shirt",
    slug: "adidas-fit-shirt",
    image: "../images/p2.jpg",
    category: "Shirts",
    price: 100,
    countInStock: 20,
    brand: "Adidas",
    rating: 4.0,
    numReviews: 10,
    description: "Original Adidas high quality T-shirt, material cotton 100%",
  },
  {
    name: "Lacosta Free Pants",
    slug: "lacosta-free-pants",
    image: "../images/p3.jpg",
    category: "Pants",
    price: 220,
    countInStock: 0,
    brand: "lacosta",
    rating: 4.8,
    numReviews: 17,
    description: "Original Lacosta high quality Pants",
  },
  {
    name: "Nike Slim Pants",
    slug: "nike-slim-pants",
    image: "../images/p4.jpg",
    category: "Pants",
    price: 78,
    countInStock: 15,
    brand: "lacosta",
    rating: 4.5,
    numReviews: 14,
    description: "High quality original nike slim pants",
  },
  {
    name: "The North Face Camping Shirt",
    slug: "adidas-running-tee",
    image: "../images/p5.jpg",
    category: "Tees",
    price: 120,
    countInStock: 15,
    brand: "Columbia",
    rating: 3.955943393403885,
    numReviews: 24,
    description: "Jordan high quality item, material varies",
  },
  {
    name: "Skechers Walking Tee",
    slug: "jordan-basketball-jersey",
    image: "../images/p6.jpg",
    category: "Tops",
    price: 160,
    countInStock: 25,
    brand: "Jordan",
    rating: 3.9489953835553493,
    numReviews: 6,
    description: "Mountain Hardwear high quality item, material varies",
  },
  {
    name: "Puma Golf Polo",
    slug: "new-balance-running-shirt",
    image: "../images/p8.jpg",
    category: "Tops",
    price: 110,
    countInStock: 20,
    brand: "Converse",
    rating: 3.420762011470694,
    numReviews: 32,
    description: "Reebok high quality item, material varies",
  },
  {
    name: "New Balance Running Shirt",
    slug: "asics-tennis-shirt",
    image: "../images/p9.jpg",
    category: "Polos",
    price: 160,
    countInStock: 5,
    brand: "Patagonia",
    rating: 3.0781463934155457,
    numReviews: 12,
    description: "Salomon high quality item, material varies",
  },
  {
    name: "Brooks Running Tee",
    slug: "vans-skateboarding-tee",
    image: "../images/p10.jpg",
    category: "Tees",
    price: 130,
    countInStock: 30,
    brand: "Hoka One One",
    rating: 4.324005750283957,
    numReviews: 48,
    description: "Reebok high quality item, material varies",
  },
  {
    name: "Adidas Running Tee",
    slug: "puma-golf-polo",
    image: "../images/p12.jpg",
    category: "Polos",
    price: 150,
    countInStock: 45,
    brand: "Nike",
    rating: 4.513480331888568,
    numReviews: 6,
    description: "Nike high quality item, material varies",
  },
  {
    name: "Patagonia Outdoor Tee",
    slug: "arc'teryx-alpine-polo",
    image: "../images/p13.jpg",
    category: "Polos",
    price: 110,
    countInStock: 30,
    brand: "Salomon",
    rating: 3.1069408574207626,
    numReviews: 29,
    description: "Patagonia high quality item, material varies",
  },
  {
    name: "Arc'teryx Alpine Polo",
    slug: "merrell-hiking-polo",
    image: "../images/p16.jpg",
    category: "Shirts",
    price: 150,
    countInStock: 35,
    brand: "New Balance",
    rating: 3.737786362762925,
    numReviews: 28,
    description: "Brooks high quality item, material varies",
  },
  {
    name: "Patagonia Outdoor Tee",
    slug: "brooks-running-tee",
    image: "../images/p17.jpg",
    category: "Tees",
    price: 140,
    countInStock: 5,
    brand: "Jordan",
    rating: 3.109532766193582,
    numReviews: 16,
    description: "Merrell high quality item, material varies",
  },
  {
    name: "Reebok Crossfit Tee",
    slug: "hoka-one-one-trail-shirt",
    image: "../images/p18.jpg",
    category: "Jerseys",
    price: 170,
    countInStock: 40,
    brand: "Skechers",
    rating: 3.5927694689660497,
    numReviews: 20,
    description: "Merrell high quality item, material varies",
  },
  {
    name: "Converse Casual Shirt",
    slug: "skechers-walking-tee",
    image: "../images/p19.jpg",
    category: "Polos",
    price: 180,
    countInStock: 10,
    brand: "Converse",
    rating: 4.8685616001183325,
    numReviews: 3,
    description: "Arc'teryx high quality item, material varies",
  },
  {
    name: "Mountain Hardwear Climbing Tee",
    slug: "reebok-crossfit-tee",
    image: "../images/p24.jpg",
    category: "Jerseys",
    price: 90,
    countInStock: 25,
    brand: "Converse",
    rating: 3.5162853544668153,
    numReviews: 8,
    description: "Jordan high quality item, material varies",
  },
];

export const sampleUsers: User[] = [
  {
    name: "Mike",
    email: "admin@example.com",
    password: bcrypt.hashSync("123456"),
    phoneNumber: 593121314,
    isAdmin: true,
  },
  {
    name: "Jerry",
    email: "user@example.com",
    password: bcrypt.hashSync("123456"),
    phoneNumber: 589131415,
    isAdmin: false,
  },
];
